### ISSUE TITLE
How to run the program ?

### ISSUE THREAD

**Issue by zx3e** [amirvalhalla/ProxyMiner#7]
How to operate the tool main.py not exist

**Comment by amirvalhalla** [comment]
Hi @zx3e,

The project is currently under development. Although it supports two sources with SOCKS4, SOCKS5, HTTP, and HTTPS protocols, it does not perform well due to synchronization requests, etc.

Please be patient; we will release it as soon as possible.

By the way, if you want to run the program, you can use the command `make run`, which requires two things:

1. You need to have the `Makefile` tool installed.
2. You should have Python version 3.12 or higher.
